/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "一个vuepress网站",
  "description": "一个vuepress学习项目",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Java基础知识",
      "frontmatter": {
        "title": "Java基础知识"
      },
      "regularPath": "/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.html",
      "relativePath": "Java基础知识.md",
      "key": "v-09a459a9",
      "path": "/Java%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.html",
      "headers": [
        {
          "level": 2,
          "title": "基础概念与常识",
          "slug": "基础概念与常识"
        },
        {
          "level": 3,
          "title": "Java 语言有哪些特点?",
          "slug": "java-语言有哪些特点"
        },
        {
          "level": 3,
          "title": "JVM vs JDK vs JRE",
          "slug": "jvm-vs-jdk-vs-jre"
        },
        {
          "level": 3,
          "title": "为什么说 Java 语言“编译与解释并存”？",
          "slug": "为什么说-java-语言-编译与解释并存"
        },
        {
          "level": 3,
          "title": "Oracle JDK 和 OpenJDK 的对比",
          "slug": "oracle-jdk-和-openjdk-的对比"
        },
        {
          "level": 3,
          "title": "Java 和 C++的区别?",
          "slug": "java-和-c-的区别"
        },
        {
          "level": 3,
          "title": "import java 和 javax 有什么区别？",
          "slug": "import-java-和-javax-有什么区别"
        },
        {
          "level": 2,
          "title": "基本语法",
          "slug": "基本语法"
        },
        {
          "level": 3,
          "title": "字符型常量和字符串常量的区别?",
          "slug": "字符型常量和字符串常量的区别"
        },
        {
          "level": 3,
          "title": "注释",
          "slug": "注释"
        },
        {
          "level": 3,
          "title": "标识符和关键字的区别是什么？",
          "slug": "标识符和关键字的区别是什么"
        },
        {
          "level": 3,
          "title": "Java 中有哪些常见的关键字？",
          "slug": "java-中有哪些常见的关键字"
        },
        {
          "level": 3,
          "title": "自增自减运算符",
          "slug": "自增自减运算符"
        },
        {
          "level": 3,
          "title": "continue、break、和 return 的区别是什么？",
          "slug": "continue、break、和-return-的区别是什么"
        },
        {
          "level": 3,
          "title": "Java 泛型了解么？什么是类型擦除？介绍一下常用的通配符？",
          "slug": "java-泛型了解么-什么是类型擦除-介绍一下常用的通配符"
        },
        {
          "level": 3,
          "title": "==和 equals 的区别",
          "slug": "和-equals-的区别"
        },
        {
          "level": 3,
          "title": "hashCode()与 equals()",
          "slug": "hashcode-与-equals"
        },
        {
          "level": 2,
          "title": "基本数据类型",
          "slug": "基本数据类型"
        },
        {
          "level": 3,
          "title": "Java 中的几种基本数据类型是什么？对应的包装类型是什么？各自占用多少字节呢？",
          "slug": "java-中的几种基本数据类型是什么-对应的包装类型是什么-各自占用多少字节呢"
        },
        {
          "level": 3,
          "title": "自动装箱与拆箱",
          "slug": "自动装箱与拆箱"
        },
        {
          "level": 3,
          "title": "8 种基本类型的包装类和常量池",
          "slug": "_8-种基本类型的包装类和常量池"
        },
        {
          "level": 2,
          "title": "方法（函数）",
          "slug": "方法-函数"
        },
        {
          "level": 3,
          "title": "什么是方法的返回值?",
          "slug": "什么是方法的返回值"
        },
        {
          "level": 3,
          "title": "方法有哪几种类型？",
          "slug": "方法有哪几种类型"
        },
        {
          "level": 3,
          "title": "在一个静态方法内调用一个非静态成员为什么是非法的?",
          "slug": "在一个静态方法内调用一个非静态成员为什么是非法的"
        },
        {
          "level": 3,
          "title": "静态方法和实例方法有何不同？",
          "slug": "静态方法和实例方法有何不同"
        },
        {
          "level": 3,
          "title": "为什么 Java 中只有值传递？",
          "slug": "为什么-java-中只有值传递"
        },
        {
          "level": 3,
          "title": "重载和重写的区别",
          "slug": "重载和重写的区别"
        },
        {
          "level": 3,
          "title": "深拷贝 vs 浅拷贝",
          "slug": "深拷贝-vs-浅拷贝"
        },
        {
          "level": 2,
          "title": "Java 面向对象",
          "slug": "java-面向对象"
        },
        {
          "level": 3,
          "title": "面向对象和面向过程的区别",
          "slug": "面向对象和面向过程的区别"
        },
        {
          "level": 3,
          "title": "成员变量与局部变量的区别有哪些？",
          "slug": "成员变量与局部变量的区别有哪些"
        },
        {
          "level": 3,
          "title": "创建一个对象用什么运算符?对象实体与对象引用有何不同?",
          "slug": "创建一个对象用什么运算符-对象实体与对象引用有何不同"
        },
        {
          "level": 3,
          "title": "对象的相等与指向他们的引用相等,两者有什么不同?",
          "slug": "对象的相等与指向他们的引用相等-两者有什么不同"
        },
        {
          "level": 3,
          "title": "一个类的构造方法的作用是什么? 若一个类没有声明构造方法，该程序能正确执行吗? 为什么?",
          "slug": "一个类的构造方法的作用是什么-若一个类没有声明构造方法-该程序能正确执行吗-为什么"
        },
        {
          "level": 3,
          "title": "构造方法有哪些特点？是否可被 override?",
          "slug": "构造方法有哪些特点-是否可被-override"
        },
        {
          "level": 3,
          "title": "面向对象三大特征",
          "slug": "面向对象三大特征"
        },
        {
          "level": 3,
          "title": "String StringBuffer 和 StringBuilder 的区别是什么? String 为什么是不可变的?",
          "slug": "string-stringbuffer-和-stringbuilder-的区别是什么-string-为什么是不可变的"
        },
        {
          "level": 3,
          "title": "Object 类的常见方法总结",
          "slug": "object-类的常见方法总结"
        },
        {
          "level": 2,
          "title": "反射",
          "slug": "反射"
        },
        {
          "level": 3,
          "title": "何为反射？",
          "slug": "何为反射"
        },
        {
          "level": 3,
          "title": "反射机制优缺点",
          "slug": "反射机制优缺点"
        },
        {
          "level": 3,
          "title": "反射的应用场景",
          "slug": "反射的应用场景"
        },
        {
          "level": 2,
          "title": "异常",
          "slug": "异常"
        },
        {
          "level": 3,
          "title": "Java 异常类层次结构图",
          "slug": "java-异常类层次结构图"
        },
        {
          "level": 3,
          "title": "Throwable 类常用方法",
          "slug": "throwable-类常用方法"
        },
        {
          "level": 3,
          "title": "try-catch-finally",
          "slug": "try-catch-finally"
        },
        {
          "level": 3,
          "title": "使用 try-with-resources 来代替try-catch-finally",
          "slug": "使用-try-with-resources-来代替try-catch-finally"
        },
        {
          "level": 2,
          "title": "I/O 流",
          "slug": "i-o-流"
        },
        {
          "level": 3,
          "title": "什么是序列化?什么是反序列化?",
          "slug": "什么是序列化-什么是反序列化"
        },
        {
          "level": 3,
          "title": "Java 序列化中如果有些字段不想进行序列化，怎么办？",
          "slug": "java-序列化中如果有些字段不想进行序列化-怎么办"
        },
        {
          "level": 3,
          "title": "获取用键盘输入常用的两种方法",
          "slug": "获取用键盘输入常用的两种方法"
        },
        {
          "level": 3,
          "title": "Java 中 IO 流分为几种?",
          "slug": "java-中-io-流分为几种"
        },
        {
          "level": 3,
          "title": "既然有了字节流,为什么还要有字符流?",
          "slug": "既然有了字节流-为什么还要有字符流"
        },
        {
          "level": 2,
          "title": "4. 参考",
          "slug": "_4-参考"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/logo.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "Created By Zhang 2021 | 鄂ICP备2021015510号 | made by vuepress"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-fb7049f0",
      "path": "/",
      "lastUpdated": "2021年9月11日星期六下午4点01分"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "navbar": false,
        "title": "关于我"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-08d62473",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 2,
          "title": "一级标题2",
          "slug": "一级标题2"
        },
        {
          "level": 2,
          "title": "一级标题3",
          "slug": "一级标题3"
        },
        {
          "level": 2,
          "title": "一级标题4",
          "slug": "一级标题4"
        }
      ],
      "lastUpdated": "2021年9月11日星期六下午4点01分"
    },
    {
      "title": "滕王阁序",
      "frontmatter": {
        "title": "滕王阁序"
      },
      "regularPath": "/article.html",
      "relativePath": "article.md",
      "key": "v-7ab7ba53",
      "path": "/article.html",
      "lastUpdated": "2021年9月6日星期一下午2点33分"
    },
    {
      "title": "CountUp 第三方组件",
      "frontmatter": {
        "title": "CountUp 第三方组件"
      },
      "regularPath": "/countup.html",
      "relativePath": "countup.md",
      "key": "v-16300ad3",
      "path": "/countup.html",
      "lastUpdated": "2021年9月7日星期二下午3点13分"
    },
    {
      "title": "CSS",
      "frontmatter": {
        "title": "CSS"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-4bb8748d",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "你好 CSS",
          "slug": "你好-css"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "c-ccc",
      "frontmatter": {
        "title": "c-ccc"
      },
      "regularPath": "/css/c-ccc.html",
      "relativePath": "css/c-ccc.md",
      "key": "v-64afa3b4",
      "path": "/css/c-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "HTML",
      "frontmatter": {
        "title": "HTML"
      },
      "regularPath": "/html/",
      "relativePath": "html/README.md",
      "key": "v-3720ab4b",
      "path": "/html/",
      "headers": [
        {
          "level": 2,
          "title": "你好 HTML",
          "slug": "你好-html"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "h-aaa",
      "frontmatter": {
        "title": "h-aaa"
      },
      "regularPath": "/html/h-aaa.html",
      "relativePath": "html/h-aaa.md",
      "key": "v-2f941b08",
      "path": "/html/h-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "h-bbb",
      "frontmatter": {
        "title": "h-bbb"
      },
      "regularPath": "/html/h-bbb.html",
      "relativePath": "html/h-bbb.md",
      "key": "v-0172b9ba",
      "path": "/html/h-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "h-ccc",
      "frontmatter": {
        "title": "h-ccc"
      },
      "regularPath": "/html/h-ccc.html",
      "relativePath": "html/h-ccc.md",
      "key": "v-1aaf80f8",
      "path": "/html/h-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "JavaScript",
      "frontmatter": {
        "title": "JavaScript"
      },
      "regularPath": "/javascript/",
      "relativePath": "javascript/README.md",
      "key": "v-665ec0cb",
      "path": "/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "你好 JavaScript",
          "slug": "你好-javascript"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "j-aaa",
      "frontmatter": {
        "title": "j-aaa"
      },
      "regularPath": "/javascript/j-aaa.html",
      "relativePath": "javascript/j-aaa.md",
      "key": "v-bc010298",
      "path": "/javascript/j-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "c-aaa",
      "frontmatter": {
        "title": "c-aaa"
      },
      "regularPath": "/css/c-aaa.html",
      "relativePath": "css/c-aaa.md",
      "key": "v-0ce55166",
      "path": "/css/c-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "c-bbb",
      "frontmatter": {
        "title": "c-bbb"
      },
      "regularPath": "/css/c-bbb.html",
      "relativePath": "css/c-bbb.md",
      "key": "v-6d46bfc6",
      "path": "/css/c-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "j-bbb",
      "frontmatter": {
        "title": "j-bbb"
      },
      "regularPath": "/javascript/j-bbb.html",
      "relativePath": "javascript/j-bbb.md",
      "key": "v-6c772ab2",
      "path": "/javascript/j-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "j-ccc",
      "frontmatter": {
        "title": "j-ccc"
      },
      "regularPath": "/javascript/j-ccc.html",
      "relativePath": "javascript/j-ccc.md",
      "key": "v-36eed6b0",
      "path": "/javascript/j-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/logo.png",
    "sidebar": {
      "/html/": [
        "h-aaa",
        "h-bbb",
        "h-ccc"
      ],
      "/css/": [
        "c-aaa",
        "c-bbb",
        "c-ccc"
      ],
      "/javascript/": [
        "j-aaa",
        "j-bbb",
        "j-ccc"
      ],
      "/pages/java/basis/": [
        "Java基础知识",
        "Java基础知识疑难点",
        "Java常见关键字总结"
      ],
      "/": [
        "",
        "about",
        "/html/",
        "/css/",
        "/javascript/",
        "/pages/java/basis/"
      ]
    },
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "了解更多",
        "link": "/about"
      },
      {
        "text": "项目",
        "items": [
          {
            "text": "前端",
            "items": [
              {
                "text": "ProjectA",
                "link": "/"
              },
              {
                "text": "ProjectB",
                "link": "/about"
              }
            ]
          },
          {
            "text": "后端",
            "items": [
              {
                "text": "ProjectC",
                "link": "/about"
              }
            ]
          },
          {
            "text": "全栈",
            "items": [
              {
                "text": "ProjectD",
                "link": "/"
              },
              {
                "text": "ProjectE",
                "link": "/about"
              }
            ]
          }
        ]
      },
      {
        "text": "面试相关",
        "items": [
          {
            "text": "Java",
            "items": [
              {
                "text": "basis0",
                "link": "/Java基础知识/",
                "target": "_self"
              },
              {
                "text": "basis1",
                "link": "/pages/java/basis/Java基础知识/",
                "target": "_self"
              },
              {
                "text": "basis2",
                "link": "/pages/java/basis/Java常见关键字总结/",
                "target": "_self"
              },
              {
                "text": "basis3",
                "link": "/pages/java/basis/Java基础知识疑难点/",
                "target": "_self"
              }
            ]
          },
          {
            "text": "后端",
            "items": [
              {
                "text": "ProjectC",
                "link": "/about"
              }
            ]
          },
          {
            "text": "全栈",
            "items": [
              {
                "text": "ProjectD",
                "link": "/"
              },
              {
                "text": "ProjectE",
                "link": "/about"
              }
            ]
          }
        ]
      },
      {
        "text": "基础知识",
        "link": "/knowledge/",
        "target": "_self",
        "rel": ""
      },
      {
        "text": "leetcode算法",
        "link": "/article/",
        "target": "_self"
      },
      {
        "text": "关于我",
        "link": "https://github.com/yitoumiemie/",
        "target": "_blank"
      }
    ]
  }
}