/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-fb7049f0",
      "path": "/"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "navbar": false
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-08d62473",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "./public/assets/img/logo.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about"
      },
      {
        "text": "Languages",
        "items": [
          {
            "text": "中文",
            "items": [
              {
                "text": "简中",
                "link": "/about"
              },
              {
                "text": "繁中",
                "link": "/"
              }
            ]
          },
          {
            "text": "English",
            "items": [
              {
                "text": "BritishEnglish",
                "link": "/"
              },
              {
                "text": "AmericaEnglish",
                "link": "/"
              }
            ]
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com",
        "target": "_self",
        "rel": ""
      },
      {
        "text": "Guide",
        "link": "/guide/",
        "target": "_blank"
      }
    ]
  }
}