/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "一个vuepress网站",
  "description": "一个vuepress学习项目",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/logo.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "Created By Zhang 2021 | 鄂ICP备2021015510号 | made by vuepress"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-fb7049f0",
      "path": "/",
      "lastUpdated": "2021年8月6日星期五下午4点48分"
    },
    {
      "title": "滕王阁序",
      "frontmatter": {
        "title": "滕王阁序"
      },
      "regularPath": "/article.html",
      "relativePath": "article.md",
      "key": "v-7ab7ba53",
      "path": "/article.html",
      "lastUpdated": "2021年9月6日星期一下午2点33分"
    },
    {
      "title": "关于我",
      "frontmatter": {
        "navbar": false,
        "title": "关于我"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-08d62473",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 2,
          "title": "一级标题2",
          "slug": "一级标题2"
        },
        {
          "level": 2,
          "title": "一级标题3",
          "slug": "一级标题3"
        },
        {
          "level": 2,
          "title": "一级标题4",
          "slug": "一级标题4"
        }
      ],
      "lastUpdated": "2021年9月7日星期二下午3点13分"
    },
    {
      "title": "CountUp 第三方组件",
      "frontmatter": {
        "title": "CountUp 第三方组件"
      },
      "regularPath": "/countup.html",
      "relativePath": "countup.md",
      "key": "v-16300ad3",
      "path": "/countup.html",
      "lastUpdated": "2021年9月7日星期二下午3点13分"
    },
    {
      "title": "CSS",
      "frontmatter": {
        "title": "CSS"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-4bb8748d",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "你好 CSS",
          "slug": "你好-css"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "c-aaa",
      "frontmatter": {
        "title": "c-aaa"
      },
      "regularPath": "/css/c-aaa.html",
      "relativePath": "css/c-aaa.md",
      "key": "v-0ce55166",
      "path": "/css/c-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "c-bbb",
      "frontmatter": {
        "title": "c-bbb"
      },
      "regularPath": "/css/c-bbb.html",
      "relativePath": "css/c-bbb.md",
      "key": "v-6d46bfc6",
      "path": "/css/c-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "c-ccc",
      "frontmatter": {
        "title": "c-ccc"
      },
      "regularPath": "/css/c-ccc.html",
      "relativePath": "css/c-ccc.md",
      "key": "v-64afa3b4",
      "path": "/css/c-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "HTML",
      "frontmatter": {
        "title": "HTML"
      },
      "regularPath": "/html/",
      "relativePath": "html/README.md",
      "key": "v-3720ab4b",
      "path": "/html/",
      "headers": [
        {
          "level": 2,
          "title": "你好 HTML",
          "slug": "你好-html"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "h-aaa",
      "frontmatter": {
        "title": "h-aaa"
      },
      "regularPath": "/html/h-aaa.html",
      "relativePath": "html/h-aaa.md",
      "key": "v-2f941b08",
      "path": "/html/h-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "h-bbb",
      "frontmatter": {
        "title": "h-bbb"
      },
      "regularPath": "/html/h-bbb.html",
      "relativePath": "html/h-bbb.md",
      "key": "v-0172b9ba",
      "path": "/html/h-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "h-ccc",
      "frontmatter": {
        "title": "h-ccc"
      },
      "regularPath": "/html/h-ccc.html",
      "relativePath": "html/h-ccc.md",
      "key": "v-1aaf80f8",
      "path": "/html/h-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "JavaScript",
      "frontmatter": {
        "title": "JavaScript"
      },
      "regularPath": "/javascript/",
      "relativePath": "javascript/README.md",
      "key": "v-665ec0cb",
      "path": "/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "你好 JavaScript",
          "slug": "你好-javascript"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "j-aaa",
      "frontmatter": {
        "title": "j-aaa"
      },
      "regularPath": "/javascript/j-aaa.html",
      "relativePath": "javascript/j-aaa.md",
      "key": "v-bc010298",
      "path": "/javascript/j-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "j-bbb",
      "frontmatter": {
        "title": "j-bbb"
      },
      "regularPath": "/javascript/j-bbb.html",
      "relativePath": "javascript/j-bbb.md",
      "key": "v-6c772ab2",
      "path": "/javascript/j-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    },
    {
      "title": "j-ccc",
      "frontmatter": {
        "title": "j-ccc"
      },
      "regularPath": "/javascript/j-ccc.html",
      "relativePath": "javascript/j-ccc.md",
      "key": "v-36eed6b0",
      "path": "/javascript/j-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "三级标题1",
          "slug": "三级标题1-2"
        },
        {
          "level": 3,
          "title": "三级标题2",
          "slug": "三级标题2-2"
        },
        {
          "level": 3,
          "title": "三级标题3",
          "slug": "三级标题3-2"
        }
      ],
      "lastUpdated": "2021年6月21日星期一晚上9点45分"
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/logo.png",
    "sidebar": {
      "/html/": [
        "h-aaa",
        "h-bbb",
        "h-ccc"
      ],
      "/css/": [
        "c-aaa",
        "c-bbb",
        "c-ccc"
      ],
      "/javascript/": [
        "j-aaa",
        "j-bbb",
        "j-ccc"
      ],
      "/": [
        "",
        "about",
        "/html/",
        "/css/",
        "/javascript/"
      ]
    },
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "了解更多",
        "link": "/about"
      },
      {
        "text": "项目",
        "items": [
          {
            "text": "前端",
            "items": [
              {
                "text": "ProjectA",
                "link": "/"
              },
              {
                "text": "ProjectB",
                "link": "/about"
              }
            ]
          },
          {
            "text": "后端",
            "items": [
              {
                "text": "ProjectC",
                "link": "/about"
              }
            ]
          },
          {
            "text": "全栈",
            "items": [
              {
                "text": "ProjectD",
                "link": "/"
              },
              {
                "text": "ProjectE",
                "link": "/about"
              }
            ]
          }
        ]
      },
      {
        "text": "面试相关",
        "items": [
          {
            "text": "Java",
            "items": [
              {
                "text": "basis",
                "link": "/pages/java/basis/Java基础知识/"
              },
              {
                "text": "basis",
                "link": "/pages/java/basis/Java常见关键字总结/"
              },
              {
                "text": "basis",
                "link": "/pages/java/basis/Java基础知识疑难点/"
              }
            ]
          },
          {
            "text": "后端",
            "items": [
              {
                "text": "ProjectC",
                "link": "/about"
              }
            ]
          },
          {
            "text": "全栈",
            "items": [
              {
                "text": "ProjectD",
                "link": "/"
              },
              {
                "text": "ProjectE",
                "link": "/about"
              }
            ]
          }
        ]
      },
      {
        "text": "基础知识",
        "link": "/knowledge/",
        "target": "_self",
        "rel": ""
      },
      {
        "text": "leetcode算法",
        "link": "/article/",
        "target": "_self"
      },
      {
        "text": "关于我",
        "link": "https://github.com/yitoumiemie/",
        "target": "_blank"
      }
    ]
  }
}